### ISSUE TITLE
CI: fix GH actions

### ISSUE THREAD

**Issue by Adminixtrator** [AeroRust/are-we-in-space-yet#11]
@elpiel 
@o0Ignition0o

**Comment by elpiel** [comment]
What does "fast asleep" means?
Also, there is a notification on travis-ci.com to use travis-ci.org for builds since 15th of June as they are ceasing them.

**Comment by Adminixtrator** [comment]
"fast asleep" - Idle

The title though..
I think I have a better idea!

**Comment by elpiel** [comment]
I've added a Workflow for deploying the site using an Action.
I'll remove travis once this passes.

FYI @Adminixtrator I've changed the base branch to `main` instead of `master`

https://github.com/AeroRust/are-we-in-space-yet/blob/453f8618ba0b0b911e6c2773d98c7838a6c566c6/.github/workflows/deploy.yml
