### ISSUE TITLE
Github key should be enough to give information about a crate commits

### ISSUE THREAD

**Issue by elpiel** [AeroRust/are-we-in-space-yet#18]
In recent changes https://github.com/AeroRust/are-we-in-space-yet/pull/16 ( by @Adminixtrator ) a feature was added that shows a score, last commit, etc for a crate.

There is a problem when no `repository` key is added, even though there is a `github` key - no statistics is show for the repository.

The key `github` should be enough to extract the same information as from the `repository` one.

![Screenshot from 2021-10-30 13-46-22](https://user-images.githubusercontent.com/8925621/139529763-1eeebd85-1679-4943-a3b2-3469521d95dd.png)

**Comment by MoralCode** [comment]
oh lol i noticed this too and was just about to report it

**Comment by MoralCode** [comment]
just took a look at this and it seems like the `github` and `repository` keys have duplicate information and that the ruby script for generating the github information is using the `repository` key to populate the `github` key. since the repository key is new in that PR you mentioned, I think it makes more sense to remove it and have its value be generated by concatenating "https://github.com/" to the contents of the Github key
